from pathlib import Path
p = Path('public/dashboard.html')
text = p.read_text(encoding='utf-8')
old = "            doc.addFileToVFS('UnifrakturMaguntia.ttf', embeddedUnifrakturFont);\n            doc.addFont('UnifrakturMaguntia.ttf', 'UnifrakturMaguntia', 'normal');\n            const pageWidth = doc.internal.pageSize.getWidth();\n"
new = "            doc.addFileToVFS(\n              'UnifrakturMaguntia.ttf',\n              embeddedUnifrakturFontBase64,\n            );\n            doc.addFont('UnifrakturMaguntia.ttf', 'UnifrakturMaguntia', 'normal');\n            const pageWidth = doc.internal.pageSize.getWidth();\n"
if old not in text:
    raise SystemExit('addFileToVFS block not found')
text = text.replace(old, new, 1)
old2 = "              const { footerTop } = getFooterLayout();\n              const availableTableHeight = Math.max(40, footerTop - startY - 2);\n              const cellHeight = availableTableHeight / (rowsPerPage + 1);\n              const cellPadding = 0.5;\n\n              // Draw header row (no fill, white background from page)\n              doc.setTextColor(0, 0, 0);\n              doc.setFont(undefined, \"bold\");\n\n              let xPos = 10;\n\n              tableHeader.forEach((title, idx) => {\n                const cellWidth = actualColWidths[idx];\n                doc.setDrawColor(0, 0, 0);\n                doc.setLineWidth(0.4);\n                doc.rect(xPos, yPos, cellWidth, cellHeight, \"S\");\n\n                // Reduce font size for long column headers\n                doc.setFontSize(idx === 3 ? 5.5 : 6);\n\n                // Use black text in table header\n                doc.setTextColor(0, 0, 0);\n                doc.text(\n                  title,\n                  xPos + cellWidth / 2,\n                  yPos + cellHeight / 2 + 1,\n                  {\n                    align: \"center\",\n                    maxWidth: cellWidth - 1,\n                  },\n                );\n                xPos += cellWidth;\n              });\n"
new2 = "              const { footerTop } = getFooterLayout();\n              const availableTableHeight = Math.max(40, footerTop - startY - 2);\n              const cellHeight = availableTableHeight / (rowsPerPage + 1);\n              const cellPadding = 0.5;\n\n              // Draw header row (no fill, white background from page)\n              doc.setTextColor(0, 0, 0);\n              doc.setFont(undefined, \"bold\");\n\n              let xPos = 10;\n\n              tableHeader.forEach((title, idx) => {\n                const cellWidth = actualColWidths[idx];\n                doc.setFillColor(230, 230, 230);\n                doc.rect(xPos, yPos, cellWidth, cellHeight, \"F\");\n                doc.setDrawColor(0, 0, 0);\n                doc.setLineWidth(0.4);\n                doc.rect(xPos, yPos, cellWidth, cellHeight, \"S\");\n\n                // Reduce font size for long column headers\n                doc.setFontSize(idx === 3 ? 5.5 : 6);\n                doc.setFont(undefined, \"bold\");\n\n                // Use black text in table header\n                doc.setTextColor(0, 0, 0);\n                doc.text(\n                  title,\n                  xPos + cellWidth / 2,\n                  yPos + cellHeight / 2 + 1,\n                  {\n                    align: \"center\",\n                    maxWidth: cellWidth - 1,\n                  },\n                );\n                xPos += cellWidth;\n              });\n"
if old2 not in text:
    raise SystemExit('table header block not found')
text = text.replace(old2, new2, 1)
p.write_text(text, encoding='utf-8')
print('updated addFileToVFS and header blocks')
